/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck;

import apideck.ats.apideck.models.errors.SDKError;
import apideck.ats.apideck.models.operations.SDKMethodInterfaces.*;
import apideck.ats.apideck.utils.HTTPClient;
import apideck.ats.apideck.utils.HTTPRequest;
import apideck.ats.apideck.utils.JSON;
import apideck.ats.apideck.utils.SerializedBody;
import apideck.ats.apideck.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Optional;
import org.apache.http.NameValuePair;
import org.openapitools.jackson.nullable.JsonNullable;

public class Applicants implements
            MethodCallApplicantsAdd,
            MethodCallApplicantsAll,
            MethodCallApplicantsDelete,
            MethodCallApplicantsOne,
            MethodCallApplicantsUpdate {

    private final SDKConfiguration sdkConfiguration;

    Applicants(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public apideck.ats.apideck.models.operations.ApplicantsAddRequestBuilder add() {
        return new apideck.ats.apideck.models.operations.ApplicantsAddRequestBuilder(this);
    }

    /**
     * Create Applicant
     * Create Applicant
     * @param request The request object containing all of the parameters for the API call.
     * @return The response from the API call.
     * @throws Exception if the API call fails.
     */
    public apideck.ats.apideck.models.operations.ApplicantsAddResponse add(
            apideck.ats.apideck.models.operations.ApplicantsAddRequest request) throws Exception {

        String baseUrl = this.sdkConfiguration.serverUrl;

        String url = apideck.ats.apideck.utils.Utils.generateURL(
                baseUrl,
                "/ats/applicants");

        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        Object _convertedRequest = Utils.convertToShape(request, Utils.JsonShape.DEFAULT,
            new TypeReference<apideck.ats.apideck.models.operations.ApplicantsAddRequest>() {});
        SerializedBody serializedRequestBody = apideck.ats.apideck.utils.Utils.serializeRequestBody(
                _convertedRequest, "applicant", "json", false);
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", this.sdkConfiguration.userAgent);

        java.util.List<NameValuePair> queryParams = apideck.ats.apideck.utils.Utils.getQueryParams(
                apideck.ats.apideck.models.operations.ApplicantsAddRequest.class, request, this.sdkConfiguration.globals);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }

        java.util.Map<String, java.util.List<String>> headers = apideck.ats.apideck.utils.Utils.getHeaders(request, this.sdkConfiguration.globals);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }

        HTTPClient client = apideck.ats.apideck.utils.Utils.configureSecurityClient(
                this.sdkConfiguration.defaultClient, this.sdkConfiguration.securitySource.getSecurity());

        HttpResponse<InputStream> httpRes = client.send(req);

        String contentType = httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        apideck.ats.apideck.models.operations.ApplicantsAddResponse.Builder resBuilder = 
            apideck.ats.apideck.models.operations.ApplicantsAddResponse
                .builder()
                .contentType(contentType)
                .statusCode(httpRes.statusCode())
                .rawResponse(httpRes);

        apideck.ats.apideck.models.operations.ApplicantsAddResponse res = resBuilder.build();

        res.withRawResponse(httpRes);

        if (httpRes.statusCode() == 201) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.CreateApplicantResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.CreateApplicantResponse>() {});
                res.withCreateApplicantResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 400) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.BadRequestResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.BadRequestResponse>() {});
                res.withBadRequestResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 401) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnauthorizedResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnauthorizedResponse>() {});
                res.withUnauthorizedResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 402) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.PaymentRequiredResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.PaymentRequiredResponse>() {});
                res.withPaymentRequiredResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 404) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.NotFoundResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.NotFoundResponse>() {});
                res.withNotFoundResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 422) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnprocessableResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnprocessableResponse>() {});
                res.withUnprocessableResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }else {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnexpectedErrorResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnexpectedErrorResponse>() {});
                res.withUnexpectedErrorResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }

        return res;
    }


    public apideck.ats.apideck.models.operations.ApplicantsAllRequestBuilder all() {
        return new apideck.ats.apideck.models.operations.ApplicantsAllRequestBuilder(this);
    }

    /**
     * List Applicants
     * List Applicants
     * @param request The request object containing all of the parameters for the API call.
     * @return The response from the API call.
     * @throws Exception if the API call fails.
     */
    public apideck.ats.apideck.models.operations.ApplicantsAllResponse all(
            apideck.ats.apideck.models.operations.ApplicantsAllRequest request) throws Exception {

        String baseUrl = this.sdkConfiguration.serverUrl;

        String url = apideck.ats.apideck.utils.Utils.generateURL(
                baseUrl,
                "/ats/applicants");

        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", this.sdkConfiguration.userAgent);

        java.util.List<NameValuePair> queryParams = apideck.ats.apideck.utils.Utils.getQueryParams(
                apideck.ats.apideck.models.operations.ApplicantsAllRequest.class, request, this.sdkConfiguration.globals);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }

        java.util.Map<String, java.util.List<String>> headers = apideck.ats.apideck.utils.Utils.getHeaders(request, this.sdkConfiguration.globals);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }

        HTTPClient client = apideck.ats.apideck.utils.Utils.configureSecurityClient(
                this.sdkConfiguration.defaultClient, this.sdkConfiguration.securitySource.getSecurity());

        HttpResponse<InputStream> httpRes = client.send(req);

        String contentType = httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        apideck.ats.apideck.models.operations.ApplicantsAllResponse.Builder resBuilder = 
            apideck.ats.apideck.models.operations.ApplicantsAllResponse
                .builder()
                .contentType(contentType)
                .statusCode(httpRes.statusCode())
                .rawResponse(httpRes);

        apideck.ats.apideck.models.operations.ApplicantsAllResponse res = resBuilder.build();

        res.withRawResponse(httpRes);

        if (httpRes.statusCode() == 200) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.GetApplicantsResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.GetApplicantsResponse>() {});
                res.withGetApplicantsResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 400) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.BadRequestResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.BadRequestResponse>() {});
                res.withBadRequestResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 401) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnauthorizedResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnauthorizedResponse>() {});
                res.withUnauthorizedResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 402) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.PaymentRequiredResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.PaymentRequiredResponse>() {});
                res.withPaymentRequiredResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 404) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.NotFoundResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.NotFoundResponse>() {});
                res.withNotFoundResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 422) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnprocessableResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnprocessableResponse>() {});
                res.withUnprocessableResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }else {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnexpectedErrorResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnexpectedErrorResponse>() {});
                res.withUnexpectedErrorResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }

        return res;
    }


    public apideck.ats.apideck.models.operations.ApplicantsDeleteRequestBuilder delete() {
        return new apideck.ats.apideck.models.operations.ApplicantsDeleteRequestBuilder(this);
    }

    /**
     * Delete Applicant
     * Delete Applicant
     * @param request The request object containing all of the parameters for the API call.
     * @return The response from the API call.
     * @throws Exception if the API call fails.
     */
    public apideck.ats.apideck.models.operations.ApplicantsDeleteResponse delete(
            apideck.ats.apideck.models.operations.ApplicantsDeleteRequest request) throws Exception {

        String baseUrl = this.sdkConfiguration.serverUrl;

        String url = apideck.ats.apideck.utils.Utils.generateURL(
                apideck.ats.apideck.models.operations.ApplicantsDeleteRequest.class,
                baseUrl,
                "/ats/applicants/{id}",
                request, this.sdkConfiguration.globals);

        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", this.sdkConfiguration.userAgent);

        java.util.List<NameValuePair> queryParams = apideck.ats.apideck.utils.Utils.getQueryParams(
                apideck.ats.apideck.models.operations.ApplicantsDeleteRequest.class, request, this.sdkConfiguration.globals);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }

        java.util.Map<String, java.util.List<String>> headers = apideck.ats.apideck.utils.Utils.getHeaders(request, this.sdkConfiguration.globals);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }

        HTTPClient client = apideck.ats.apideck.utils.Utils.configureSecurityClient(
                this.sdkConfiguration.defaultClient, this.sdkConfiguration.securitySource.getSecurity());

        HttpResponse<InputStream> httpRes = client.send(req);

        String contentType = httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        apideck.ats.apideck.models.operations.ApplicantsDeleteResponse.Builder resBuilder = 
            apideck.ats.apideck.models.operations.ApplicantsDeleteResponse
                .builder()
                .contentType(contentType)
                .statusCode(httpRes.statusCode())
                .rawResponse(httpRes);

        apideck.ats.apideck.models.operations.ApplicantsDeleteResponse res = resBuilder.build();

        res.withRawResponse(httpRes);

        if (httpRes.statusCode() == 200) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.DeleteApplicantResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.DeleteApplicantResponse>() {});
                res.withDeleteApplicantResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 400) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.BadRequestResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.BadRequestResponse>() {});
                res.withBadRequestResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 401) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnauthorizedResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnauthorizedResponse>() {});
                res.withUnauthorizedResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 402) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.PaymentRequiredResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.PaymentRequiredResponse>() {});
                res.withPaymentRequiredResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 404) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.NotFoundResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.NotFoundResponse>() {});
                res.withNotFoundResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 422) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnprocessableResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnprocessableResponse>() {});
                res.withUnprocessableResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }else {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnexpectedErrorResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnexpectedErrorResponse>() {});
                res.withUnexpectedErrorResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }

        return res;
    }


    public apideck.ats.apideck.models.operations.ApplicantsOneRequestBuilder one() {
        return new apideck.ats.apideck.models.operations.ApplicantsOneRequestBuilder(this);
    }

    /**
     * Get Applicant
     * Get Applicant
     * @param request The request object containing all of the parameters for the API call.
     * @return The response from the API call.
     * @throws Exception if the API call fails.
     */
    public apideck.ats.apideck.models.operations.ApplicantsOneResponse one(
            apideck.ats.apideck.models.operations.ApplicantsOneRequest request) throws Exception {

        String baseUrl = this.sdkConfiguration.serverUrl;

        String url = apideck.ats.apideck.utils.Utils.generateURL(
                apideck.ats.apideck.models.operations.ApplicantsOneRequest.class,
                baseUrl,
                "/ats/applicants/{id}",
                request, this.sdkConfiguration.globals);

        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", this.sdkConfiguration.userAgent);

        java.util.List<NameValuePair> queryParams = apideck.ats.apideck.utils.Utils.getQueryParams(
                apideck.ats.apideck.models.operations.ApplicantsOneRequest.class, request, this.sdkConfiguration.globals);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }

        java.util.Map<String, java.util.List<String>> headers = apideck.ats.apideck.utils.Utils.getHeaders(request, this.sdkConfiguration.globals);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }

        HTTPClient client = apideck.ats.apideck.utils.Utils.configureSecurityClient(
                this.sdkConfiguration.defaultClient, this.sdkConfiguration.securitySource.getSecurity());

        HttpResponse<InputStream> httpRes = client.send(req);

        String contentType = httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        apideck.ats.apideck.models.operations.ApplicantsOneResponse.Builder resBuilder = 
            apideck.ats.apideck.models.operations.ApplicantsOneResponse
                .builder()
                .contentType(contentType)
                .statusCode(httpRes.statusCode())
                .rawResponse(httpRes);

        apideck.ats.apideck.models.operations.ApplicantsOneResponse res = resBuilder.build();

        res.withRawResponse(httpRes);

        if (httpRes.statusCode() == 200) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.GetApplicantResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.GetApplicantResponse>() {});
                res.withGetApplicantResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 400) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.BadRequestResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.BadRequestResponse>() {});
                res.withBadRequestResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 401) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnauthorizedResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnauthorizedResponse>() {});
                res.withUnauthorizedResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 402) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.PaymentRequiredResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.PaymentRequiredResponse>() {});
                res.withPaymentRequiredResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 404) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.NotFoundResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.NotFoundResponse>() {});
                res.withNotFoundResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 422) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnprocessableResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnprocessableResponse>() {});
                res.withUnprocessableResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }else {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnexpectedErrorResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnexpectedErrorResponse>() {});
                res.withUnexpectedErrorResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }

        return res;
    }


    public apideck.ats.apideck.models.operations.ApplicantsUpdateRequestBuilder update() {
        return new apideck.ats.apideck.models.operations.ApplicantsUpdateRequestBuilder(this);
    }

    /**
     * Update Applicant
     * Update Applicant
     * @param request The request object containing all of the parameters for the API call.
     * @return The response from the API call.
     * @throws Exception if the API call fails.
     */
    public apideck.ats.apideck.models.operations.ApplicantsUpdateResponse update(
            apideck.ats.apideck.models.operations.ApplicantsUpdateRequest request) throws Exception {

        String baseUrl = this.sdkConfiguration.serverUrl;

        String url = apideck.ats.apideck.utils.Utils.generateURL(
                apideck.ats.apideck.models.operations.ApplicantsUpdateRequest.class,
                baseUrl,
                "/ats/applicants/{id}",
                request, this.sdkConfiguration.globals);

        HTTPRequest req = new HTTPRequest();
        req.setMethod("PATCH");
        req.setURL(url);
        Object _convertedRequest = Utils.convertToShape(request, Utils.JsonShape.DEFAULT,
            new TypeReference<apideck.ats.apideck.models.operations.ApplicantsUpdateRequest>() {});
        SerializedBody serializedRequestBody = apideck.ats.apideck.utils.Utils.serializeRequestBody(
                _convertedRequest, "applicant", "json", false);
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", this.sdkConfiguration.userAgent);

        java.util.List<NameValuePair> queryParams = apideck.ats.apideck.utils.Utils.getQueryParams(
                apideck.ats.apideck.models.operations.ApplicantsUpdateRequest.class, request, this.sdkConfiguration.globals);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }

        java.util.Map<String, java.util.List<String>> headers = apideck.ats.apideck.utils.Utils.getHeaders(request, this.sdkConfiguration.globals);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }

        HTTPClient client = apideck.ats.apideck.utils.Utils.configureSecurityClient(
                this.sdkConfiguration.defaultClient, this.sdkConfiguration.securitySource.getSecurity());

        HttpResponse<InputStream> httpRes = client.send(req);

        String contentType = httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        apideck.ats.apideck.models.operations.ApplicantsUpdateResponse.Builder resBuilder = 
            apideck.ats.apideck.models.operations.ApplicantsUpdateResponse
                .builder()
                .contentType(contentType)
                .statusCode(httpRes.statusCode())
                .rawResponse(httpRes);

        apideck.ats.apideck.models.operations.ApplicantsUpdateResponse res = resBuilder.build();

        res.withRawResponse(httpRes);

        if (httpRes.statusCode() == 200) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UpdateApplicantResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UpdateApplicantResponse>() {});
                res.withUpdateApplicantResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 400) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.BadRequestResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.BadRequestResponse>() {});
                res.withBadRequestResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 401) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnauthorizedResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnauthorizedResponse>() {});
                res.withUnauthorizedResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 402) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.PaymentRequiredResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.PaymentRequiredResponse>() {});
                res.withPaymentRequiredResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 404) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.NotFoundResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.NotFoundResponse>() {});
                res.withNotFoundResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        } else if (httpRes.statusCode() == 422) {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnprocessableResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnprocessableResponse>() {});
                res.withUnprocessableResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }else {
            if (apideck.ats.apideck.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                apideck.ats.apideck.models.shared.UnexpectedErrorResponse out = mapper.readValue(
                    Utils.toUtf8AndClose(httpRes.body()),
                    new TypeReference<apideck.ats.apideck.models.shared.UnexpectedErrorResponse>() {});
                res.withUnexpectedErrorResponse(java.util.Optional.ofNullable(out));
            } else {
                throw new SDKError(httpRes, httpRes.statusCode(), "Unknown content-type received: " + contentType, Utils.toByteArrayAndClose(httpRes.body()));
            }
        }

        return res;
    }

}
