/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck;

import apideck.ats.apideck.models.operations.SDKMethodInterfaces.*;
import apideck.ats.apideck.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class Ats {

    private final SDKConfiguration sdkConfiguration;
    private final Applicants applicants;
    private final Applications applications;
    private final Jobs jobs;

    Ats(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.applicants = new Applicants(this.sdkConfiguration);
        this.applications = new Applications(this.sdkConfiguration);
        this.jobs = new Jobs(this.sdkConfiguration);
    }

    public final Applicants applicants() {
        return applicants;
    }

    public final Applications applications() {
        return applications;
    }

    public final Jobs jobs() {
        return jobs;
    }
}
