/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ApplicationStatus {
    OPEN("open"),
    REJECTED("rejected"),
    HIRED("hired"),
    CONVERTED("converted"),
    OTHER("other");

    @JsonValue
    public final String value;

    private ApplicationStatus(String value) {
        this.value = value;
    }
}
