/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ApplicationInput {
    @JsonProperty("applicant_id")
    public String applicantId;

    public ApplicationInput withApplicantId(String applicantId) {
        this.applicantId = applicantId;
        return this;
    }
    
    @JsonProperty("job_id")
    public String jobId;

    public ApplicationInput withJobId(String jobId) {
        this.jobId = jobId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stage")
    public ApplicationStage stage;

    public ApplicationInput withStage(ApplicationStage stage) {
        this.stage = stage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public ApplicationStatus status;

    public ApplicationInput withStatus(ApplicationStatus status) {
        this.status = status;
        return this;
    }
    
    public ApplicationInput(@JsonProperty("applicant_id") String applicantId, @JsonProperty("job_id") String jobId) {
        this.applicantId = applicantId;
        this.jobId = jobId;
  }
}
