/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CustomField {
    /**
     * More information about the custom field
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public CustomField withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Unique identifier for the custom field.
     */
    @JsonProperty("id")
    public String id;

    public CustomField withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Name of the custom field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public CustomField withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public Object value;

    public CustomField withValue(Object value) {
        this.value = value;
        return this;
    }
    
    public CustomField(@JsonProperty("id") String id) {
        this.id = id;
  }
}
