/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EmailType - Email type
 */
public enum EmailType {
    PRIMARY("primary"),
    SECONDARY("secondary"),
    WORK("work"),
    PERSONAL("personal"),
    BILLING("billing"),
    OTHER("other");

    @JsonValue
    public final String value;

    private EmailType(String value) {
        this.value = value;
    }
}
