/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class JobBlocks {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("content")
    public String content;

    public JobBlocks withContent(String content) {
        this.content = content;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;

    public JobBlocks withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public JobBlocks(){}
}
