/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum JobLinksType {
    JOB_PORTAL("job_portal"),
    JOB_DESCRIPTION("job_description");

    @JsonValue
    public final String value;

    private JobLinksType(String value) {
        this.value = value;
    }
}
