/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class JobLinks {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public JobLinksType type;

    public JobLinks withType(JobLinksType type) {
        this.type = type;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public JobLinks withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public JobLinks(){}
}
