/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class JobSalary {
    /**
     * Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("currency")
    public Currency currency;

    public JobSalary withCurrency(Currency currency) {
        this.currency = currency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("interval")
    public String interval;

    public JobSalary withInterval(String interval) {
        this.interval = interval;
        return this;
    }
    
    /**
     * Maximum salary payable for the job role.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max")
    public Long max;

    public JobSalary withMax(Long max) {
        this.max = max;
        return this;
    }
    
    /**
     * Minimum salary payable for the job role.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("min")
    public Long min;

    public JobSalary withMin(Long min) {
        this.min = min;
        return this;
    }
    
    public JobSalary(){}
}
