/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * JobStatus - The status of the job.
 */
public enum JobStatus {
    DRAFT("draft"),
    INTERNAL("internal"),
    PUBLISHED("published"),
    COMPLETED("completed"),
    ON_HOLD("on-hold"),
    PRIVATE_("private");

    @JsonValue
    public final String value;

    private JobStatus(String value) {
        this.value = value;
    }
}
