/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * JobVisibility - The visibility of the job
 */
public enum JobVisibility {
    DRAFT("draft"),
    PUBLIC_("public"),
    INTERNAL("internal");

    @JsonValue
    public final String value;

    private JobVisibility(String value) {
        this.value = value;
    }
}
