/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MetaCursors - Cursors to navigate to previous or next pages through the API
 */

public class MetaCursors {
    /**
     * Cursor to navigate to the current page of results through the API
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("current")
    public String current;

    public MetaCursors withCurrent(String current) {
        this.current = current;
        return this;
    }
    
    /**
     * Cursor to navigate to the next page of results through the API
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("next")
    public String next;

    public MetaCursors withNext(String next) {
        this.next = next;
        return this;
    }
    
    /**
     * Cursor to navigate to the previous page of results through the API
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous")
    public String previous;

    public MetaCursors withPrevious(String previous) {
        this.previous = previous;
        return this;
    }
    
    public MetaCursors(){}
}
