/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PhoneNumber {
    /**
     * The area code of the phone number, e.g. 323
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("area_code")
    public String areaCode;

    public PhoneNumber withAreaCode(String areaCode) {
        this.areaCode = areaCode;
        return this;
    }
    
    /**
     * The country code of the phone number, e.g. +1
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country_code")
    public String countryCode;

    public PhoneNumber withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * The extension of the phone number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("extension")
    public String extension;

    public PhoneNumber withExtension(String extension) {
        this.extension = extension;
        return this;
    }
    
    /**
     * Unique identifier of the phone number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public PhoneNumber withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The phone number
     */
    @JsonProperty("number")
    public String number;

    public PhoneNumber withNumber(String number) {
        this.number = number;
        return this;
    }
    
    /**
     * The type of phone number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public PhoneNumberType type;

    public PhoneNumber withType(PhoneNumberType type) {
        this.type = type;
        return this;
    }
    
    public PhoneNumber(@JsonProperty("number") String number) {
        this.number = number;
  }
}
