/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ApplicantsUpdateResponse {
    /**
     * Bad Request
     */
    
    public apideck.ats.apideck.models.shared.BadRequestResponse badRequestResponse;

    public ApplicantsUpdateResponse withBadRequestResponse(apideck.ats.apideck.models.shared.BadRequestResponse badRequestResponse) {
        this.badRequestResponse = badRequestResponse;
        return this;
    }
    
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public ApplicantsUpdateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The specified resource was not found
     */
    
    public apideck.ats.apideck.models.shared.NotFoundResponse notFoundResponse;

    public ApplicantsUpdateResponse withNotFoundResponse(apideck.ats.apideck.models.shared.NotFoundResponse notFoundResponse) {
        this.notFoundResponse = notFoundResponse;
        return this;
    }
    
    /**
     * Payment Required
     */
    
    public apideck.ats.apideck.models.shared.PaymentRequiredResponse paymentRequiredResponse;

    public ApplicantsUpdateResponse withPaymentRequiredResponse(apideck.ats.apideck.models.shared.PaymentRequiredResponse paymentRequiredResponse) {
        this.paymentRequiredResponse = paymentRequiredResponse;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public ApplicantsUpdateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public ApplicantsUpdateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthorized
     */
    
    public apideck.ats.apideck.models.shared.UnauthorizedResponse unauthorizedResponse;

    public ApplicantsUpdateResponse withUnauthorizedResponse(apideck.ats.apideck.models.shared.UnauthorizedResponse unauthorizedResponse) {
        this.unauthorizedResponse = unauthorizedResponse;
        return this;
    }
    
    /**
     * Unexpected error
     */
    
    public apideck.ats.apideck.models.shared.UnexpectedErrorResponse unexpectedErrorResponse;

    public ApplicantsUpdateResponse withUnexpectedErrorResponse(apideck.ats.apideck.models.shared.UnexpectedErrorResponse unexpectedErrorResponse) {
        this.unexpectedErrorResponse = unexpectedErrorResponse;
        return this;
    }
    
    /**
     * Unprocessable
     */
    
    public apideck.ats.apideck.models.shared.UnprocessableResponse unprocessableResponse;

    public ApplicantsUpdateResponse withUnprocessableResponse(apideck.ats.apideck.models.shared.UnprocessableResponse unprocessableResponse) {
        this.unprocessableResponse = unprocessableResponse;
        return this;
    }
    
    /**
     * Applicants
     */
    
    public apideck.ats.apideck.models.shared.UpdateApplicantResponse updateApplicantResponse;

    public ApplicantsUpdateResponse withUpdateApplicantResponse(apideck.ats.apideck.models.shared.UpdateApplicantResponse updateApplicantResponse) {
        this.updateApplicantResponse = updateApplicantResponse;
        return this;
    }
    
    public ApplicantsUpdateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
