/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.shared;

import apideck.ats.apideck.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public enum EmploymentTerms {
    FULL_TIME("full-time"),
    PART_TIME("part-time"),
    INTERNSHIP("internship"),
    CONTRACTOR("contractor"),
    EMPLOYEE("employee"),
    FREELANCE("freelance"),
    TEMP("temp"),
    SEASONAL("seasonal"),
    VOLUNTEER("volunteer"),
    OTHER("other");

    @JsonValue
    private final String value;

    private EmploymentTerms(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
