/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.operations;

import apideck.ats.apideck.models.errors.SDKError;
import apideck.ats.apideck.utils.LazySingletonValue;
import apideck.ats.apideck.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class ApplicationsUpdateRequestBuilder {

    private ApplicationsUpdateRequest request;
    private final SDKMethodInterfaces.MethodCallApplicationsUpdate sdk;

    public ApplicationsUpdateRequestBuilder(SDKMethodInterfaces.MethodCallApplicationsUpdate sdk) {
        this.sdk = sdk;
    }

    public ApplicationsUpdateRequestBuilder request(ApplicationsUpdateRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ApplicationsUpdateResponse call() throws Exception {

        return sdk.update(
            request);
    }
}
