/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck.models.operations;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SDKMethodInterfaces {

    public interface MethodCallApplicantsAdd {
        apideck.ats.apideck.models.operations.ApplicantsAddResponse add(
            apideck.ats.apideck.models.operations.ApplicantsAddRequest request) throws Exception;
    }


    public interface MethodCallApplicantsAll {
        apideck.ats.apideck.models.operations.ApplicantsAllResponse all(
            apideck.ats.apideck.models.operations.ApplicantsAllRequest request) throws Exception;
    }


    public interface MethodCallApplicantsDelete {
        apideck.ats.apideck.models.operations.ApplicantsDeleteResponse delete(
            apideck.ats.apideck.models.operations.ApplicantsDeleteRequest request) throws Exception;
    }


    public interface MethodCallApplicantsOne {
        apideck.ats.apideck.models.operations.ApplicantsOneResponse one(
            apideck.ats.apideck.models.operations.ApplicantsOneRequest request) throws Exception;
    }


    public interface MethodCallApplicantsUpdate {
        apideck.ats.apideck.models.operations.ApplicantsUpdateResponse update(
            apideck.ats.apideck.models.operations.ApplicantsUpdateRequest request) throws Exception;
    }


    public interface MethodCallApplicationsAdd {
        apideck.ats.apideck.models.operations.ApplicationsAddResponse add(
            apideck.ats.apideck.models.operations.ApplicationsAddRequest request) throws Exception;
    }


    public interface MethodCallApplicationsAll {
        apideck.ats.apideck.models.operations.ApplicationsAllResponse all(
            apideck.ats.apideck.models.operations.ApplicationsAllRequest request) throws Exception;
    }


    public interface MethodCallApplicationsDelete {
        apideck.ats.apideck.models.operations.ApplicationsDeleteResponse delete(
            apideck.ats.apideck.models.operations.ApplicationsDeleteRequest request) throws Exception;
    }


    public interface MethodCallApplicationsOne {
        apideck.ats.apideck.models.operations.ApplicationsOneResponse one(
            apideck.ats.apideck.models.operations.ApplicationsOneRequest request) throws Exception;
    }


    public interface MethodCallApplicationsUpdate {
        apideck.ats.apideck.models.operations.ApplicationsUpdateResponse update(
            apideck.ats.apideck.models.operations.ApplicationsUpdateRequest request) throws Exception;
    }


    public interface MethodCallJobsAll {
        apideck.ats.apideck.models.operations.JobsAllResponse all(
            apideck.ats.apideck.models.operations.JobsAllRequest request) throws Exception;
    }


    public interface MethodCallJobsOne {
        apideck.ats.apideck.models.operations.JobsOneResponse one(
            apideck.ats.apideck.models.operations.JobsOneRequest request) throws Exception;
    }

}
