/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package apideck.ats.apideck;

import apideck.ats.apideck.utils.HTTPClient;
import apideck.ats.apideck.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "9.9.2";
	public String sdkVersion = "0.2.0";
	public String genVersion = "2.173.0";
	public String userAgent = "speakeasy-sdk/java 0.2.0 2.173.0 9.9.2 <no value>";
	
	
}